steps:
  build:
    image: rust:latest
    commands:
      - rustup target add x86_64-unknown-linux-musl
      - cargo build --release --target x86_64-unknown-linux-musl
      - cp target/x86_64-unknown-linux-musl/release/me_chat_server app

  docker:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t me-chat-server:latest .
      - docker run -d -p 18080:18080 -e PORT=18080 me-chat-server:latest
